version: '3'

services:
  python3.9:
    build:
      context: .
      dockerfile: Dockerfile.py39.test
    command: >
      sh -c "flake8 src/ tests/ &&
        pylint src/ tests/ &&
        mypy --install-types --non-interactive src/ &&
        bandit -r src/ &&
        safety check &&
        pytest"

  python3.8:
    build:
      context: .
      dockerfile: Dockerfile.py38.test
    command: >
      sh -c "flake8 src/ tests/ &&
        pylint src/ tests/ &&
        pytest"

  python3.7:
    build:
      context: .
      dockerfile: Dockerfile.py37.test
    command: >
      sh -c "flake8 src/ tests/ &&
        pylint src/ tests/ &&
        pytest --cov-fail-under=0"

  python3.6:
    build:
      context: .
      dockerfile: Dockerfile.py36.test
    command: >
      sh -c "flake8 src/ tests/ &&
        pylint src/ tests/ &&
        pytest --cov-fail-under=0"
